# -*- coding: utf-8 -*-
"""klasifikasidaunpadi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DYN7avj1Bfoo7M6N0DtP3os9p7HlWKVT
"""

st.image(img, width=600)

from google.colab import files
files.download("cnn_penyakit_daun_padi.h5")

streamlit
tensorflow
numpy
pillow

import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image

# ================================
# KONFIGURASI HALAMAN
# ================================
st.set_page_config(
    page_title="Klasifikasi Penyakit Daun Padi",
    layout="centered"
)

st.title("🌾 Klasifikasi Penyakit Daun Padi")
st.write("Website ini menggunakan model CNN untuk mengklasifikasikan penyakit pada daun padi.")

# ================================
# LOAD MODEL
# ================================
@st.cache_resource
def load_model():
    model = tf.keras.models.load_model("cnn_penyakit_daun_padi.h5")
    return model

model = load_model()

# ================================
# DAFTAR KELAS (HARUS SESUAI DATASET)
# ================================
class_names = [
    "Bacterial leaf blight",
    "Brown spot",
    "Leaf smut"
]

# ================================
# UPLOAD GAMBAR
# ================================
uploaded_file = st.file_uploader(
    "Upload gambar daun padi",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file is not None:
    image = Image.open(uploaded_file).convert("RGB")
    st.image(image, caption="Gambar yang diunggah", use_column_width=True)

    # ================================
    # PREPROCESSING
    # ================================
    img = image.resize((224, 224))
    img_array = np.array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    # ================================
    # PREDIKSI
    # ================================
    predictions = model.predict(img_array)
    confidence = np.max(predictions)
    predicted_class = class_names[np.argmax(predictions)]

    # ================================
    # OUTPUT
    # ================================
    st.subheader("🧪 Hasil Klasifikasi")
    st.write(f"**Prediksi Penyakit :** {predicted_class}")
    st.write(f"**Tingkat Keyakinan :** {confidence * 100:.2f}%")

project/
│
├── app.py                     ← website utama
├── cnn_penyakit_daun_padi.h5  ← model CNN
├── requirements.txt           ← dependensi
└── README.md (opsional)

from google.colab import files
files.download("cnn_penyakit_daun_padi.h5")

!pip install streamlit

import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image

# Load model
model = tf.keras.models.load_model("cnn_penyakit_daun_padi.h5")

# Label kelas
class_names = ['Bacterial Leaf Blight', 'Brown Spot', 'Leaf Smut']

st.set_page_config(page_title="Klasifikasi Penyakit Daun Padi", layout="centered")

st.title("🌾 Klasifikasi Penyakit Daun Padi")
st.write("Aplikasi berbasis CNN untuk mengklasifikasikan penyakit daun padi")

uploaded_file = st.file_uploader("Upload citra daun padi", type=["jpg", "png", "jpeg"])

if uploaded_file is not None:
    image = Image.open(uploaded_file).convert("RGB")
    st.image(image, caption="Citra Daun Padi", use_column_width=True)

    img = image.resize((224, 224))
    img_array = np.array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    prediction = model.predict(img_array)
    predicted_class = class_names[np.argmax(prediction)]
    confidence = np.max(prediction) * 100

    st.subheader("🧠 Hasil Klasifikasi")
    st.write(f"**Penyakit** : {predicted_class}")
    st.write(f"**Tingkat Keyakinan** : {confidence:.2f}%")

history = model.fit(
    train_data,
    validation_data=val_data,
    epochs=20
)

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    train_data,
    validation_data=val_data,
    epochs=20
)

final_train_acc = history.history['accuracy'][-1]
final_val_acc = history.history['val_accuracy'][-1]

print(f"Akurasi Training Akhir  : {final_train_acc*100:.2f}%")
print(f"Akurasi Validasi Akhir  : {final_val_acc*100:.2f}%")

model.save("cnn_penyakit_daun_padi.h5")

import os
os.path.exists("/content/rice_leaf_diseases")

train_data = image_dataset_from_directory(
    DATASET_PATH,
    validation_split=0.2,
    subset="training",
    seed=123,
    image_size=(224,224),
    batch_size=16
)

val_data = image_dataset_from_directory(
    DATASET_PATH,
    validation_split=0.2,
    subset="validation",
    seed=123,
    image_size=(224,224),
    batch_size=16
)

DATASET_PATH = "/content/rice_leaf_diseases"

!ls rice_leaf_diseases

!ls

!pwd

import tensorflow as tf
from tensorflow.keras.preprocessing import image_dataset_from_directory

DATASET_PATH = "rice_leaf_diseases"
IMG_SIZE = (224, 224)
BATCH_SIZE = 16

train_data = image_dataset_from_directory(
    DATASET_PATH,
    validation_split=0.2,
    subset="training",
    seed=123,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

val_data = image_dataset_from_directory(
    DATASET_PATH,
    validation_split=0.2,
    subset="validation",
    seed=123,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout

model = Sequential([
    Conv2D(32, (3,3), activation='relu', input_shape=(224,224,3)),
    MaxPooling2D(2,2),
    Conv2D(64, (3,3), activation='relu'),
    MaxPooling2D(2,2),
    Conv2D(128, (3,3), activation='relu'),
    MaxPooling2D(2,2),
    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(3, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.save("cnn_penyakit_daun_padi.h5")

test_loss, test_accuracy = model.evaluate(validation_generator)
print("Akurasi akhir model:", test_accuracy)

import matplotlib.pyplot as plt

plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.legend()
plt.title('Grafik Akurasi Model CNN')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.show()

plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.legend()
plt.title('Grafik Loss Model CNN')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.show()

test_loss, test_accuracy = model.evaluate(validation_generator)
print("Test Accuracy:", test_accuracy)

history = model.fit(
    train_generator,
    validation_data=validation_generator,
    epochs=20
)

train_generator = datagen.flow_from_directory(
    data_dir,
    target_size=(224, 224),
    batch_size=16,
    class_mode='categorical',
    subset='training'
)

validation_generator = datagen.flow_from_directory(
    data_dir,
    target_size=(224, 224),
    batch_size=16,
    class_mode='categorical',
    subset='validation'
)

datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2
)

data_dir = 'rice_leaf_diseases'

from tensorflow.keras.preprocessing.image import ImageDataGenerator

history = model.fit(
    train_generator,
    validation_data=validation_generator,
    epochs=20
)

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout

model = Sequential([
    Conv2D(32, (3,3), activation='relu', input_shape=(224,224,3)),
    MaxPooling2D(2,2),

    Conv2D(64, (3,3), activation='relu'),
    MaxPooling2D(2,2),

    Conv2D(128, (3,3), activation='relu'),
    MaxPooling2D(2,2),

    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(3, activation='softmax')
])

model.summary()

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Parameter dasar
img_size = (224, 224)
batch_size = 16

dataset_path = "rice_leaf_diseases"

# Data generator + preprocessing
datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2
)

# Data latih
train_data = datagen.flow_from_directory(
    dataset_path,
    target_size=img_size,
    batch_size=batch_size,
    class_mode='categorical',
    subset='training'
)

# Data validasi
val_data = datagen.flow_from_directory(
    dataset_path,
    target_size=img_size,
    batch_size=batch_size,
    class_mode='categorical',
    subset='validation'
)

import os

dataset_path = "rice_leaf_diseases"

classes = os.listdir(dataset_path)
print("Kelas penyakit:", classes)

for cls in classes:
    cls_path = os.path.join(dataset_path, cls)
    print(f"{cls}: {len(os.listdir(cls_path))} gambar")

!unzip rice_leaf_diseases.zip